### ISSUE TITLE
feature request: ability to configure fence_vmware_rest via role

### ISSUE THREAD

**Issue by pob8888** [OndrejHome/ansible.ha-cluster-pacemaker#15]
In addition to the cluster_configure_fence_vmware_soap option and functionality, is it possible to add support for fence_vmware_rest with a similar config option?

I noticed there is a fence_custom which we can probably use, but as redhat are now suggesting fence_vmware_rest for environments where fence_vmware_soap is timing out, it would be nice if this was available directly from the role.

And finally, in some redhat article (which I cannot find right now - I can dig it out if you think it will help), I have seen recommendations to run only a single fence_vmware_* agent across all the nodes - rather than having one fence_vmware_* agent / stonith resource per node.  Could we add a flag to the relevant tasks to allow only one of these devices per cluster if desired?

**Comment by OndrejHome** [comment]
Hi @pob8888, thank you for nicely described feature request.

> In addition to the cluster_configure_fence_vmware_soap option and functionality, is it possible to add support for  fence_vmware_rest with a similar config option?

Yes, this looks easy enough to be added. I'm thinking about adding the `cluster_configure_fence_vmware_rest` and re-using the other `fence_vmware_*` options as long as that makes sense.

> I noticed there is a fence_custom which we can probably use, but as redhat are now suggesting fence_vmware_rest for environments where fence_vmware_soap is timing out, it would be nice if this was available directly from the role.
> And finally, in some redhat article (which I cannot find right now - I can dig it out if you think it will help), I have seen recommendations to run only a single fence_vmware_* agent across all the nodes - rather than having one fence_vmware_* agent / stonith resource per node. Could we add a flag to the relevant tasks to allow only one of these devices per cluster if desired?

I wonder which article it is. In case you find it and you can provided it here, thanks in advance. 
As a reason for using one device instead of multiple I can imagine login limits which can be on vmware side (like maximum concurrent connections of same user).  As for ability to configure single stonith device instead of multiple it makes sense to me as configurable option. 

I expect to have time to prepare some testing code over this or next weekend. I can easily test 'single vs multiple' stonith devices options as the fence_kdump agent in this role could be configured in both ways easily. However for fence_vmware_rest I don't have any testing system to verify it on.

@pob8888 if there is code with fence_vmware_rest configuration would you be able to test it out? I ask because I feel more comfortable when made changes are tested with real stuff.

In any case I will get back to you once I have some testing code (most probably in `devel`) and will let you know it can be tested.
Thank you for nice feature suggestion.

**Comment by pob8888** [comment]
> > In addition to the cluster_configure_fence_vmware_soap option and functionality, is it possible to add support for  fence_vmware_rest with a similar config option?
> 
> Yes, this looks easy enough to be added. I'm thinking about adding the `cluster_configure_fence_vmware_rest` and re-using the other `fence_vmware_*` options as long as that makes sense.

That makes perfect sense - the parameters used by both fence_vmware_soap and fence_vmware_rest are the same.

> > I noticed there is a fence_custom which we can probably use, but as redhat are now suggesting fence_vmware_rest for environments where fence_vmware_soap is timing out, it would be nice if this was available directly from the role.
> > And finally, in some redhat article (which I cannot find right now - I can dig it out if you think it will help), I have seen recommendations to run only a single fence_vmware_* agent across all the nodes - rather than having one fence_vmware_* agent / stonith resource per node. Could we add a flag to the relevant tasks to allow only one of these devices per cluster if desired?
> 
> I wonder which article it is. In case you find it and you can provided it here, thanks in advance.

I have found reference to it in this document: https://access.redhat.com/solutions/667443 (

> As a reason for using one device instead of multiple I can imagine login limits which can be on vmware side (like maximum concurrent connections of same user). As for ability to configure single stonith device instead of multiple it makes sense to me as configurable option.
> 
> I expect to have time to prepare some testing code over this or next weekend. I can easily test 'single vs multiple' stonith devices options as the fence_kdump agent in this role could be configured in both ways easily. However for fence_vmware_rest I don't have any testing system to verify it on.
> 
> @pob8888 if there is code with fence_vmware_rest configuration would you be able to test it out? I ask because I feel more comfortable when made changes are tested with real stuff.

absolutely - I would be happy to test the changes once available - but please dont feel this should be a priority to implement.... I can always tweak the stonith config post-deployment in the meantime - I just think having this as a native feature of your role would give more flexibility.

> In any case I will get back to you once I have some testing code (most probably in `devel`) and will let you know it can be tested.
> Thank you for nice feature suggestion.

Thank you for taking the time to read and respond - I will keep an eye on this page and test when you are ready.

Regards
Richard

**Comment by OndrejHome** [comment]
Hi Richard,

Thank you for link and response. Once there is something to test I will let you know here.

Ondrej

**Comment by OndrejHome** [comment]
Hi Richard (@pob8888 )
I have just pushed a testing code to [`develop` branch](https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/tree/develop) with both ability to configure `fence_vmware_rest` and option to configure `fence_vmware_rest` as single device in cluster to fence all nodes instead of one device per node. There is also new example playbook in [README(develop)](https://github.com/OndrejHome/ansible.ha-cluster-pacemaker/blob/develop/README.md) illustrating the use of these two features together (**Example playbook E**)

For now I have added this 'one-device-per-cluster' option only to `fence_vmware_rest` to get initial feedback from you, if that works OK I plan to add this to `fence_kdump`, `fence_vmware_soap` and `fence_xvm`.

`fence_vmware_rest` seems to have no binary on EL6 so role will report failure when attempting to configure it there. Rest of platforms looks OK (EL7, EL8, F31).

One limitation that I'm aware of: Currently all `cluster_configure_fence_*` creates stonith devices with same name pattern, so it is not possible to combine multiple stonith devices as their configuration gets overwritten (except fence-kdump). So for example it is not possible to configure `fence_vmware_soap` and `fence_vmware_rest` with one device per node at this time. I hope this is not needed, but mentioning it here just in case.

When you find some time to give the changes test please leave me feedback for change and its documentation here.
Once again thank you your time!

**Comment by pob8888** [comment]
Hi Ondrej,

I have done some initial testing at home with the develop branch, and so far, the created stonith resource looks exactly like I would have expected, and everything else is still working as before.
I dont have a vcentre/esx setup here at home - I will test it fully at work at some point this week, but wanted to give initial feedback that I get the results I would expect.

I used the examples from the documentation pretty much as-is without any issue so that is also good.

I'll get back to you at some point in the next week.
- thank you for taking the time to implement this so quickly.

**Comment by pob8888** [comment]
Hi again,
  I have now tested this against actual vcentre and esx's.
I am happy to say, it just works - exactly as described.

Also, to add, you mentioned you might  plan to add this cluster_configure_stonith_style: 'one-device-per-cluster' flag to some of the other agents...  If you do that, I can also test the fence_vmware_soap agent in this mode.

Once again - thanks for your help on this one.
Regards
Richard

**Comment by OndrejHome** [comment]
Hi Richard,

I have pushed the additional changes in commit 5fac3bc6c8d21936f56272ef1ee030623b52e0d8 to `develop` for support of 'one-device-per-cluster' in `fence_kdump`, `fence_xvm` and `fence_vmware_soap`.
After that there is one small commit that applies only to Fedora (missing dependency).

If you can give it a try with `fence_vmware_soap` I would then merge this whole change into `master` and give it a new tag so it can be installed also from Ansible Galaxy.

Thank you for feedback, testing and quick response!

**Comment by pob8888** [comment]
I have tested this morning using 'one-device-per-cluster'.
I tested with both the fence_vmware_rest, and fence_vmware_soap agents - and both worked fine.
I also did one extra test (by mistake), where I had both cluster_configure_fence_vmware_soap *and* cluster_configure_fence_vmware_rest set.... and it successfully created me one of each type.

Specifically, I used this:
- { role: ansible.ha-cluster-pacemaker, cluster_name: '{{ local_cluster_name }}' , cluster_configure_fence_xvm: false,  cluster_configure_fence_vmware_soap: true, enable_pcsd_gui: 'false', cluster_etc_hosts: false, enable_repos: false, cluster_configure_fence_vmware_rest: true, cluster_configure_stonith_style: 'one-device-per-cluster' }

All looks good.  thanks again

Regards
Richard

**Comment by OndrejHome** [comment]
Hi Richard,

Thank you for testing and feedback. I have just pushed changes from `develop` into `master`, tagged them with version `28.0.0` and pushed them to [Ansible galaxy](https://galaxy.ansible.com/OndrejHome/ha-cluster-pacemaker).

I will be closing this issue now, but in case there is problem feel free to post again here or create a new one.
And of course if you get any other good ideas for improvements or hit some issue with role, you are welcomed.
Thank you and have a great day!

Ondrej (온드레이)
